### ISSUE TITLE
Change Output 

### ISSUE THREAD

**Issue by gurnoor1990** [PBR/QTL-prioritisation#1]
Output should contain the following columns:

GENE_ID, GENE_ALIAS, UNIPROT_ID, PROTEIN_DESCRIPTION, CHROMOSOME_NUMBER, GENE_LOCATION, PRIORITIZATION SCORE

EXAMPLE OF [Solyc09g010090.2](http://pbg-ld.candygene-nlesc.surf-hosted.nl:8890/describe/?url=http%3A%2F%2Flocalhost%3A8890%2Fgenome%2FSolanum_lycopersicum%2Fgene%2FSolyc09g010090.2&sid=2) 

GENE_ID -> Solyc09g010090.2

GENE_ALIAS -> [Lin7](http://pbg-ld.candygene-nlesc.surf-hosted.nl:8890/describe/?url=http%3A%2F%2Fpurl.uniprot.org%2Funiprot%2FQ8L4N2%23gene-MD580AAF568F6D9C26040BF17F97A3C7904&sid=2). Here TRIPLE is UNIPROT_ID [encodeby](http://pbg-ld.candygene-nlesc.surf-hosted.nl:8890/describe/?url=http%3A%2F%2Fpurl.uniprot.org%2Fcore%2FencodedBy&sid=2) GENE_ALIAS

UNIPROT_ID -> [Q8L4N2](http://pbg-ld.candygene-nlesc.surf-hosted.nl:8890/describe/?url=http%3A%2F%2Fpurl.uniprot.org%2Funiprot%2FQ8L4N2&sid=2)

PROTEIN_DESCRIPTION -> Cell-wall invertase. TRIPLE UNIPROT_ID [DC:description](http://pbg-ld.candygene-nlesc.surf-hosted.nl:8890/describe/?url=http%3A%2F%2Fpurl.org%2Fdc%2Felements%2F1.1%2Fdescription&sid=2) PROTEIN_DESCRIPTION

CHROMOSOME_NUMBER -> 9

GENE_LOCATION ->3480545-3484159

PRIORITIZATION SCORE -> FINAL PVALUE

**Comment by gurnoor1990** [comment]
Please do it only for QTLSearch algorithm.

**Comment by matthijsbrouwer** [comment]
Information about gene (alias, location) and protein (uniprot_id/description) is collected and added to the report for QTLSearch
